"""empty message

Revision ID: 875244ac5644
Revises: 40d7bc3032ad
Create Date: 2021-06-12 13:43:37.939339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875244ac5644'
down_revision = '40d7bc3032ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'description', new_column_name='seeking_description')
    op.alter_column('artist', 'looking_for_venues', new_column_name='seeking_venue')
    op.alter_column('venue', 'description', new_column_name='seeking_description')
    op.alter_column('venue', 'looking_for_talent', new_column_name='seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'seeking_description', new_column_name='description')
    op.alter_column('artist', 'seeking_venue', new_column_name='looking_for_venues')
    op.alter_column('venue', 'seeking_description', new_column_name='description')
    op.alter_column('venue', 'seeking_talent', new_column_name='looking_for_talent')
    # ### end Alembic commands ###
